name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: true
          SHOW_OS: false
          SHOW_TITLE: true
          TIME_RANGE: last_14_days
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_COMMIT: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
